### ISSUE TITLE
Button type is not properly overridden

### ISSUE THREAD

**Issue by greatislander** [fluid-project/hearth#121]
## Describe the bug

Supplying a `type` to the Button component does not override the default type (`submit`).

### To reproduce

1. Use the Button component with `type="button"`.
2. Inspect the rendered view.
3. See that the button has `type="submit"`.

### Expected behavior

The button should have `type="button"`.

## Screenshots

Not applicable.

## Technical details

Not applicable.

## Additional context or notes

https://laravel.com/docs/9.x/blade#non-class-attribute-merging

**Comment by greatislander** [comment]
@chosww Maybe a good starting point for you would be taking a look at this ticket?

**Comment by chosww** [comment]
@greatislander Sounds good, I will take a look 👍

**Comment by greatislander** [comment]
@chosww One other aspect of this that would be good to include is tests for the component. Here's some information about testing components:

https://laravel.com/docs/9.x/http-tests#rendering-blade-and-components

The button tests should follow the pattern of the other tests for other components: https://github.com/fluid-project/hearth/tree/main/tests/Components

One last note, the repository uses [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/). Linking in case you haven't used them before.
