### ISSUE TITLE
Add ResourceCollection model

### ISSUE THREAD

**Issue by greatislander** [fluid-project/hearth#134]
## Is your feature request related to a problem?

For Hearth's resource library functionality, we need the ability for users to create collections of thematically related resources. This functionality is distinct from the ability to tag resources with topics, types of resource, etc. and filtering by these attributes. Resources collections will be manually curated and may contain resources that are a mix of topics/types/etc. but that are somehow related.

## Describe the solution you'd like

We should introduce a new model called `ResourceCollection` with an appropriate relationship to the existing `Resource` model. Each resource collection should also include translatable `title` and `description` fields and should belong to the `User` who created it.

## Describe alternative solutions you've considered

Not applicable.

## Additional context or notes

How to add database migrations to a Laravel package like Hearth:

- https://github.com/spatie/laravel-package-tools#working-with-migrations

See rough implementation of this here:

- https://github.com/accessibility-exchange/platform/blob/ef817e9/app/Models/ResourceCollection.php
- https://github.com/accessibility-exchange/platform/blob/ef817e9/database/migrations/2021_10_15_143529_create_resource_collections_table.php

Relevant documentation on relationships in Laravel:

- http://laravel.com/docs/9.x/eloquent-relationships

Articles on database design:

- https://tray2.se/posts/database-design
- https://tray2.se/posts/database-design-part-2

**Comment by greatislander** [comment]
> * Specify relationship ResourceCollection belongs to User in ResourceCollection.

One note here is that a user may create more than one ResourceCollection— so which kind of relationship should this be? (From [this list](https://laravel.com/docs/9.x/eloquent-relationships#defining-relationships).)

>  * ResourceCollection has a foreign key mapped to User, something like collection_id to user id

Which table should the foreign key be in— `resource_collections` or `users`? And what should the column name for the foreign key be (see this [guide to naming conventions](https://github.com/alexeymezenin/laravel-best-practices#follow-laravel-naming-conventions) for ideas).

>  * Should delete users' resource collection when user is deleted; cascade

Absolutely!

>  * ResourceCollection to Resources, one to many

Yep!

>  * ResourceCollection has a foreign key mapped to Resource, collection_id to resource id

Again, which table should the foreign key be in— `resource_collections` or `resources`? And what should the column name for the foreign key be?

**Comment by chosww** [comment]
> > * Specify relationship ResourceCollection belongs to User in ResourceCollection.
> 
> One note here is that a user may create more than one ResourceCollection— so which kind of relationship should this be? (From [this list](https://laravel.com/docs/9.x/eloquent-relationships#defining-relationships).)
>
> one to many; one user to many resource collections
>
> > * ResourceCollection has a foreign key mapped to User, something like collection_id to user id
> 
> Which table should the foreign key be in— `resource_collections` or `users`? And what should the column name for the foreign key be (see this [guide to naming conventions](https://github.com/alexeymezenin/laravel-best-practices#follow-laravel-naming-conventions) for ideas).
>
> The foreign key should be in resource_collections, and the column name to be resource_collections_id
>
> > * Should delete users' resource collection when user is deleted; cascade
> 
> Absolutely!
> 
> > * ResourceCollection to Resources, one to many
> 
> Yep!
> 
> > * ResourceCollection has a foreign key mapped to Resource, collection_id to resource id
> 
> Again, which table should the foreign key be in— `resource_collections` or `resources`? And what should the column name for the foreign key be?
>
> foreign key in resources, column name to be resources_id and that points to resource_collections table's id

**Comment by greatislander** [comment]
You correctly identified what table the foreign key column should be in, but the column name should reflect the parent model. So:

A `User` has many `ResourceCollections` — the `User` is the parent, so the `ResourceCollection` needs a foreign key called `user_id` referencing the parent.

Also, I made a mistake in my earlier comment— a `Resource` can belong to more than one `ResourceCollection`, so this should be a Many to Many relationship: see here: https://laravel.com/docs/9.x/eloquent-relationships#many-to-many
