### ISSUE TITLE
provide a way of linking to checkbox input fields

### ISSUE THREAD

**Issue by jobara** [fluid-project/hearth#148]
## Is your feature request related to a problem?

When an error occurs, it is possible to create a summary at the top of the page listing all of the validation errors. When this method is used, it is helpful to provide direct links to the inputs with errors. Laravel's error array is keyed off of the inputs name. Because most hearth components also use the value of the `name` for their `id` it is easy to setup an anchor like `#name` to link to the related field. However, with `<x-hearth-checkboxes />` the ids are suffixed with the input's value and the name field is suffixed with []. 

## Describe the solution you'd like

The first input could be generated without the value appended to the end, so that an anchor could be generated following the same pattern.

## Describe alternative solutions you've considered

Alternatively, the author would need to do special handling for checkboxes to generate the link with the correct id format.

**Comment by jobara** [comment]
@greatislander I guess that could help to at least have something close and related to link to. It would be an improvement to allow for a quick implementation. However, I think ideally you'd want to hit the input itself. In my case, I worked around the issue by writing some logic to map keys from the error bag to the anchors.

**Comment by greatislander** [comment]
In discussion, we concluded it's better to leave this to an implementer to decide. A good solution might be putting the checkboxes in a `<fieldset>` with an ID that matches the name and link to that.
