### ISSUE TITLE
Validation Error handling does not work when validating arrays of values

### ISSUE THREAD

**Issue by jobara** [fluid-project/hearth#149]
## Describe the bug

The [HandlesValidation trait](https://github.com/fluid-project/hearth/blob/49b7b1c94fc16d98e6850b173b9f8fc3c93ac4c7/src/Traits/HandlesValidation.php) doesn't handle validation of arrays. When validating an array value, the key is returned with the array index that failed validation appended to the end. So for example if the form input name is `toValidate` and the first time fails validation the error key is returned as `toValidate.0` 

### To reproduce

1. use a component like `<x-hearth-checkboxes name="toValidate" />`
2. validate the input of the array of values by having a validation rule like  `['toValidate.*' => ['min:3']`; which would check each value in the array to ensure it passes the validation rule. In real world cases this may be more likely to occur with [enum validation](https://laravel.com/docs/9.x/validation#rule-enum).
3.  Notice that values that fail are returned in the error bag keyed off of the name with the * replaced by the index. For example, toValidate.0.

### Expected behavior

`hasErrors` will return true for arrays that fail validation. Allowing the error `<x-hearth-error />` to be displayed and linked appropriately. For consistency with the radio-buttons should probably also mark the checkbox inputs with `aria-invalid`.

## Additional context or notes

[Accessible validation of checkbox and radiobutton groups](https://blog.tenon.io/accessible-validation-of-checkbox-and-radiobutton-groups/) suggests not marking all inputs in a group with aria-invalid. However, the article is a bit old, so not sure it's the best current advice.

**Comment by greatislander** [comment]
@jobara to to be clear, the issue as described in your example above is that:

1. The group's `name` is `toValidate`;
2. The validation errors in the `MessageBag` are keyed to the array, e.g. `toValidate.0`, `toValidate.1`, etc.;
3. `HandlesValidation` only looks for an error called `toValidate` and this returns a false negative, indicating that the group is valid when it isn't?

If that's the issue I think the fix is fairly straight forward— I can do a substring comparison instead of looking for a specific error key.

**Comment by jobara** [comment]
> @jobara to to be clear, the issue as described in your example above is that:
> 
> 1. The group's `name` is `toValidate`;
> 2. The validation errors in the `MessageBag` are keyed to the array, e.g. `toValidate.0`, `toValidate.1`, etc.;
> 3. `HandlesValidation` only looks for an error called `toValidate` and this returns a false negative, indicating that the group is valid when it isn't?
> 
> If that's the issue I think the fix is fairly straight forward— I can do a substring comparison instead of looking for a specific error key.

@greatislander yes, that sounds about right.
