### ISSUE TITLE
No matter what locale is selected from the locale switcher, settings page always redirects to user's saved locale

### ISSUE THREAD

**Issue by greatislander** [fluid-project/hearth#82]
## Describe the bug

While on the user settings page, choosing a different locale from the locale switcher in the primary navigation doesn't change the interface to that language as the user is automatically redirected to their stored locale.

### To reproduce
1. Create an account.
2. Navigate to the user settings page.
3. Using the locale switcher in the primary navigation, select "Français".
4. Observe that the page reloads but remains in English.

### Expected behavior

The page should switch to French.

## Additional context or notes

If a user has a stored preference but switches locales from the primary menu, should their preference be used for subsequent page loads? Or should switching locales from the primary menu update their preference?

**Comment by greatislander** [comment]
@jobara Would love your input on this. I remember we ran into it on Wednesday as well.

**Comment by jobara** [comment]
@greatislander thanks for filing this issue, I missed adding it last week. 

I think you raise a good question about how switching locales in the primary menu vs preference should be handled. 

Here are my assumptions about the differences:

- Primary menu locale switching can happen without an account
- Logging in will switch the locale to what is stored in the preference
- Primary menu setting will be lost if cookies or other temp storage are cleared or expire
- Preference will be applied across browsers and devices

We might want to get some input from a designer on this. I'm leaning towards the primary menu selection persisting across pages. That's what I'd assume would happen if there were no account logged in. With that in mind, making it a sort of "shortcut" into the account preference could make sense, and would remove some confusion if they mismatch.

**Comment by greatislander** [comment]
@jobara I'll get some input from @cherylhjli and @sepidehshahi on this today as it's pertinent to our work for AinA.
