### ISSUE TITLE
Support individual hints for checkboxes and radio buttons

### ISSUE THREAD

**Issue by greatislander** [fluid-project/hearth#90]
## Is your feature request related to a problem?

Currently, the Checkboxes and Radio Buttons components support a single shared hint. In some circumstances, a unique hint may be required for each choice.

## Describe the solution you'd like

The `options` parameter can be either a simple keyed array where the key is the option `name` and the value is the option `label`, e.g.:

```php
$options = [
	'vanilla' => __('Vanilla'),
    'chocolate' => __('Chocolate'),
];
```

Or it can be a nested array where each key (`name`) points to an array with a `label` and a `hint`:

```php
$options = [
	'vanilla' => [
        'label' => __('Vanilla'),
        'hint' => __('A timeless classic.'),
    ],
    'chocolate' => [
        'label' => __('Chocolate'),
        'hint' => __('A decadent treat.'),
    ],
];
```

If hints are supplied, the `aria-describedby` attribute of each checkbox or radio button will reference the unique hint (and, if supplied, a global hint).

## Describe alternative solutions you've considered

Not applicable.

## Additional context or notes

See: https://www.figma.com/file/35NiapHpSyGcZP24H2HWZF/Ideation-Co-design-wires?node-id=236%3A10537

**Comment by greatislander** [comment]
@jobara If I'm around Monday and you have a chance, I'd love to discuss this approach with you.

**Comment by jobara** [comment]
> @jobara If I'm around Monday and you have a chance, I'd love to discuss this approach with you.

Hi @greatislander, feel free to ping me, if you're available.
